name = "taharah-website"
compatibility_date = "2024-01-01"
pages_build_output_dir = "."

[vars]
EMAIL_SERVICE = "gmail"
OWNER_EMAIL = "sss.naik2007@gmail.com"
EMAIL_USER = "sss.naik2007@gmail.com"
EMAIL_PASS = "cwswjmubelmlhaod"
FIREBASE_PROJECT_ID = "studio-7642357109-d9026"
FIREBASE_STORAGE_BUCKET = "studio-7642357109-d9026.firebasestorage.app"
FIREBASE_PRIVATE_KEY_ID = "992b031db8cbb949f66b6a71ad1dd3d434adcd7c"
FIREBASE_PRIVATE_KEY = """
-----BEGIN PRIVATE KEY-----
MIIEvAIBADANBgkqhkiG9w0BAQEFAASCBKYwggSiAgEAAoIBAQC/oZ32GBv6W/Y8
+RgMDP7x3ihrfyJjdAN0H/nYRC3kF5aE7Eh2NOmECirKb69+NCZeQtw6xW6ujSeY
L9BAIyARtPJNB8bfJthbkqoVNEHPGq11fMh29VQNDnpLeRiEpbOfhqkkMdg7vd/z
/3baXsXrOs9pnobCsAXBhfwRibnRX7nyQYUGzNzJ55sBU0fm8Vvkmpo1gCQp6IGu
2ZZSPqaMRyHZ5LGHA0R6kna5Qm926lrAe8Uogawir4+Vmy7fJnpP+sslqMdfps+N
xYjA59sFaYdqt7IxHf57J9feM33hK7znwunb7U6q+VwxL7lkfGhlrxv0CqvmX0mg
LmIf9D9pAgMBAAECggEAEPfTj9XkrE92R0HbMj34WRxNwe748Yt1PtQSAGdRFPBN
nwKlXZTgcMTfhQBmRlYAyoYgUDhQrT8Np7RzWuMcjcM3v4og8wMekwr8C1mvRI/B9
yXhqG7ZvYdSVWZd4Z05w0EBRO8Y6Glgeu3E0afOYXNLRSM3jqtuBNviRMFBcpsBG
1DGNiePwDV6WTTn1PXUe+zi08qXvLGuzTy8lZMr9ECiLWDJV4YsMlLgkSUM82sfS
Ez4BzWowqXYkUbWC8TkvCloawfjh/8fFueZGMA4qg+NjLpfnsr/nAOqBJUBOjF9J
+r3R8216/VPVCldkGSKp4AsaR7DzNrwYIED6pI5/HQKBgQDvUlzGx9FIs1+0KBnO
bufON0gWh8bTjkaBUZvoHoPBea3Qvc5UdE/INWOiYe/KKaShMQIEloVKVGc4MpEQ
n8jsif/P8XJMs3GnrTaya52oZSr/DX41DFkaYBiw/b7eLGpQxQxH6Xuuv5x4oOc/
Ysx4Addg6YJgfEtkqaLur7L8pwKBgQDM/G4hIe8YrzqrssnuT76J0uwSVMsDTXdl
7BwVWIyf2Xy1Qy/9s5eOGlwAypKQNsm5P7Y7aYhbHZw2v45vTHZKbhjBDo3qptXu
2c7uwiZ7xDPPQgu6heJTov/ipDfuKCr5b1mmye1ZY0aM6fM6D4F8P3LehM8xF2+/
icCR8UkVbwKBgBQir9+hrEAbp2+2+ATgW+yDxjLvFZFzJQd4YE+1UYyTukYX0iZU
6umDZHCjINO3kTxmrS7Jo0lPtKeLyZzGdNdB/R33yJAfgO6Eqld0qn0ile2Dqxy3
fz+y2iD6GHcE8aT+Dzx1roxTXszfbNVucJmgPgjPXMLVclpz01uVuM99AoGATuuh
OwBlnYtZe2GKfUYWhdm/Kg+bWdopbgRJi65b9e82JFOJ1pOedgeQBH35j6yIXdo5
vwYSiYIM8sctf4xgvqdEwI9p9D3nf9473ZDCYERZ7iHvghCp4qmO+yNepUKxyPcl
/SEhUJj4QKiSDHiL0dpbz3AylSQA0i2nBolvKeECgYA3iqR2yCdRuuySd74IGOM2
YMM9dCkXiwmyFZjx25Qd4JtS0OB0ZhEbvKSEALvSLBnRrh/ZRTYFe1PVq3l0yNtq
93mlu8GdYBPrmo8UFV8MhvO1/QEpresCeMwEWK46kUjWfP1b1rSph6K0zPU/tGwf
OFO/zRCU2T3QZLZmfHyVWg==
-----END PRIVATE KEY-----
"""
FIREBASE_CLIENT_EMAIL = "firebase-adminsdk-fbsvc@studio-7642357109-d9026.iam.gserviceaccount.com"
FIREBASE_CLIENT_ID = "116019966837750187800"
FIREBASE_CERT_URL = "https://www.googleapis.com/robot/v1/metadata/x509/firebase-adminsdk-fbsvc%40studio-7642357109-d9026.iam.gserviceaccount.com"
FIREBASE_API_KEY = "AIzaSyCQ9gafSnJBwuXvIpnOGn4Kwo8YqMkKY0M"
FIREBASE_APP_ID = "1:1076239216683:web:a298fa70bb136183217a6e"
FIREBASE_AUTH_DOMAIN = "studio-7642357109-d9026.firebaseapp.com"
FIREBASE_MEASUREMENT_ID = "G-ZYZ750JHMB"
FIREBASE_MESSAGING_SENDER_ID = "1076239216683"

FIREBASE_VAPID_KEY = "BLzgONy1dxvZSOupRvbC1gnjaW98YHtk683EuqQoT7sEqXsFU5R7CD_pa2Fhuem6qoVflcZr6f0rSeLpHyylzsI"
RAZORPAY_KEY_ID = "rzp_test_qZWULE2MoPHZJv"
RAZORPAY_KEY_SECRET = "dwhI00HuTIRk5T61AyUq1Bhh"

